DartScorer/Controllers/APIController.cs
using DartScorer.Models;
using DartScorer.Models.Storage;
using Newtonsoft.Json;
using System.Web.Mvc;

namespace DartScorer.Controllers
{
    public class APIController : Controller
    {
        public string Match(int id)
        {
            DartMatch match = MatchStorage.Instance.StorageItems[id];
            string json = JsonConvert.SerializeObject(match);

            return json;
        }

        public void Score(int id, string dart1, string dart2, string dart3)
        {
            ThrowGroup group = new ThrowGroup(DartValues.Parse(dart1), DartValues.Parse(dart2), DartValues.Parse(dart3));
            Score(id, group);
        }

        [NonAction]
        private void Score(int id, ThrowGroup throwGroup)
        {
            DartMatch match = MatchStorage.Instance.StorageItems[id];
            match.Score(throwGroup);
        }

        public void SaveToFile()
        {
            PlayerStorage.Instance.ExportStorageItems();
            MatchStorage.Instance.ExportStorageItems();
        }

        public void Undo(int id)
        {
            DartMatch match = MatchStorage.Instance.StorageItems[id];
            match.Undo();
        }

        public void Redo(int id)
        {
            DartMatch match = MatchStorage.Instance.StorageItems[id];
            match.Redo();
        }
    }
}

DartScorer/Controllers/HomeController.cs
using DartScorer.Models;
using DartScorer.Models.Storage;
using System;
using System.Web.Mvc;

namespace DartScorer.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            SelectList listItems = new SelectList(MatchStorage.Instance.StorageItems.Values, "ID", "DisplayName");

            return View(listItems);
        }

        [HttpPost]
        public ActionResult Index(int matchID, string gameAction)
        {
            if (gameAction == "scorer")
            {
                return RedirectToAction("Scorer", "Home", new { id = matchID });
            }

            if (gameAction == "control")
            {
                return RedirectToAction("Control", "Home", new { id = matchID });
            }

            throw new ArgumentException("Unexpected value for argument gameAction.");
        }

        [HttpGet]
        public ActionResult NewMatch()
        {
            SelectList listItems = new SelectList(PlayerStorage.Instance.StorageItems.Values, "ID", "PlayerName");

            return View(listItems);
        }

        [HttpPost]
        public ActionResult NewMatch(int player1, int player2, int startPoints, int sets, int legs)
        {
            Player player1Object = PlayerStorage.Instance.StorageItems[player1];
            Player player2Object = PlayerStorage.Instance.StorageItems[player2];

            DartMatch match = new DartMatch(player1Object, player2Object, new MatchSetting(startPoints, sets, legs, true));

            return RedirectToAction("Scorer", "Home", new { id = match.ID });
        }

        [HttpGet]
        public ActionResult NewPlayer()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewPlayer(string name)
        {
            Player newPlayer = new Player(name);

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Control(int id)
        {
            ViewBag.MatchID = id;

            return View();
        }

        public ActionResult Scorer(int id)
        {
            ViewBag.MatchID = id;

            return View();
        }
    }
}

DartScorer/Views/Home/Control.cshtml
@{
    ViewBag.Title = "Spiel steuern";
}

<div id="control">
    <div id="control_buttons">
        <input type="button" value="SBULL" /><input type="button" value="BULL" /><br />
        <input type="button" value="S20" /><input type="button" value="D20" /><input type="button" value="T20" /><br />
        <input type="button" value="S19" /><input type="button" value="D19" /><input type="button" value="T19" /><br />
        <input type="button" value="S18" /><input type="button" value="D18" /><input type="button" value="T18" /><br />
        <input type="button" value="S17" /><input type="button" value="D17" /><input type="button" value="T17" /><br />
        <input type="button" value="S16" /><input type="button" value="D16" /><input type="button" value="T16" /><br />
        <input type="button" value="S15" /><input type="button" value="D15" /><input type="button" value="T15" /><br />
        <input type="button" value="S14" /><input type="button" value="D14" /><input type="button" value="T14" /><br />
        <input type="button" value="S13" /><input type="button" value="D13" /><input type="button" value="T13" /><br />
        <input type="button" value="S12" /><input type="button" value="D12" /><input type="button" value="T12" /><br />
        <input type="button" value="S11" /><input type="button" value="D11" /><input type="button" value="T11" /><br />
        <input type="button" value="S10" /><input type="button" value="D10" /><input type="button" value="T10" /><br />
        <input type="button" value="S9" /><input type="button" value="D9" /><input type="button" value="T9" /><br />
        <input type="button" value="S8" /><input type="button" value="D8" /><input type="button" value="T8" /><br />
        <input type="button" value="S7" /><input type="button" value="D7" /><input type="button" value="T7" /><br />
        <input type="button" value="S6" /><input type="button" value="D6" /><input type="button" value="T6" /><br />
        <input type="button" value="S5" /><input type="button" value="D5" /><input type="button" value="T5" /><br />
        <input type="button" value="S4" /><input type="button" value="D4" /><input type="button" value="T4" /><br />
        <input type="button" value="S3" /><input type="button" value="D3" /><input type="button" value="T3" /><br />
        <input type="button" value="S2" /><input type="button" value="D2" /><input type="button" value="T2" /><br />
        <input type="button" value="S1" /><input type="button" value="D1" /><input type="button" value="T1" /><br />
        <input type="button" value="NOT_HIT" /><br />
    </div>

    <div id="overview">
        <input type="text" id="1" class="chosen" readonly="readonly" />
        <input type="text" id="2" readonly="readonly" />
        <input type="text" id="3" readonly="readonly" />
        <br />
        <input type="button" id="confirm" value=" BESTÄTIGEN " /><br />
        <input type="button" id="reset" value=" RESET " /><br />
        <input type="button" id="undo" value=" RÜCKGÄNGIG " /><br />
        <input type="button" id="redo" value=" WIEDERHOLEN " />
    </div>

    <table id="match_info">
        <tr id="points">
            <td class="pl1"></td>
            <td class="dec left">.</td>
            <td class="pl2"></td>
        </tr>
        <tr id="names">
            <td class="pl1"></td>
            <td class="dec"></td>
            <td class="pl2"></td>
        </tr>
        <tr id="sets">
            <td class="pl1"></td>
            <td class="dec">Sets</td>
            <td class="pl2"></td>
        </tr>
        <tr id="legs">
            <td class="pl1"></td>
            <td class="dec">Legs</td>
            <td class="pl2"></td>
        </tr>
    </table>
</div>

@Scripts.Render("~/bundles/control")

<script>
    setRequestURL("@Url.Action("Match", "API", new { id = @ViewBag.MatchID })");
    setPostURL("@Url.Action("Score", "API", new { id = @ViewBag.MatchID })");
    setUndoURL("@Url.Action("Undo", "API", new { id = @ViewBag.MatchID })");
    setRedoURL("@Url.Action("Redo", "API", new { id = @ViewBag.MatchID })");
    setSaveURL("@Url.Action("SaveToFile", "API")");
</script>

DartScorer/Views/Home/Index.cshtml
@model System.Web.Mvc.SelectList
@{
    ViewBag.Title = "Spiel auswählen";
}

<div class="gamechooser">
    <h4>Partie wählen</h4>
    @using (Html.BeginForm("Index", "Home", FormMethod.Post))
    {
        <div>
            @Html.DropDownList("matchID", Model, new { size = 5, required = "required" })
        </div>

        <div>
            @Html.RadioButton("gameAction", "scorer", true, new { id = "gameAction_scorer" })
            @Html.Label("gameAction_scorer", "Spielstand anzeigen")
        </div>

        <div>
            @Html.RadioButton("gameAction", "control", false, new { id = "gameAction_control" })
            @Html.Label("gameAction_control", "Spiel steuern")
        </div>

        <div>
            <input type="submit" value="Bestätigen" />
        </div>

        <div>
            @Html.ActionLink("Neues Spiel erstellen", "NewMatch", "Home")
        </div>

        <div>
            @Html.ActionLink("Neuen Spieler erstellen", "NewPlayer", "Home")
        </div>
    }
</div>

DartScorer/Views/Home/NewMatch.cshtml
@model System.Web.Mvc.SelectList
@{
    ViewBag.Title = "Neues Spiel";
}

<div class="gamecreator">
    @using (Html.BeginForm("NewMatch", "Home", FormMethod.Post))
    {
        @Html.Label("player1", "Name Spieler 1")
        @Html.DropDownList("player1", Model, new { required = "required" })

        @Html.Label("player2", "Name Spieler 2")
        @Html.DropDownList("player2", Model, new { required = "required" })

        @Html.Label("startPoints", "Start-Punktzahl")
        @Html.TextBox("startPoints", 501, new { type = "number", required = "required" })

        @Html.Label("sets", "Sets (Best of)")
        @Html.TextBox("sets", 1, new { type = "number", required = "required" })

        @Html.Label("legs", "Legs (Best of)")
        @Html.TextBox("legs", 4, new { type = "number", required = "required" })

        <input type="submit" value="Erstellen" />
    }
</div>

DartScorer/Views/Home/NewPlayer.cshtml
@{
    ViewBag.Title = "Neuer Spieler";
}

<div class="gamecreator">
    @using (Html.BeginForm("NewPlayer", "Home", FormMethod.Post))
    {
        @Html.Label("name", "Name des Spielers")
        @Html.TextBox("name", "", new { required = "required" })

        <input type="submit" value="Erstellen" />
    }
</div>

DartScorer/Views/Home/Scorer.cshtml
@{
    ViewBag.Title = "Scorer";
}

<div id="section">
    <div id="leg_1">
        <table id="tab1"></table>
    </div>
    <div id="scoreboard">
        <div id="match_1">
            <div class="pkte">&nbsp;</div>
            <div class="name">&nbsp;</div>
            <div class="sets">0</div>
            <div class="legs">0</div>
            <hr />
            <div class="avg">0,00</div>
            <div class="his">0</div>
            <div class="hif">0</div>
            <div class="a60">0</div>
            <div class="a100">0</div>
            <div class="a140">0</div>
        </div>
        <div id="descr">
            <div class="pkte">.</div>
            <div class="name">&nbsp;</div>
            <div class="sets">Sets</div>
            <div class="legs">Legs</div>
            <hr />
            <div class="avg">Average</div>
            <div class="his">High Score</div>
            <div class="hif">High Finish</div>
            <div class="a60">60+</div>
            <div class="a100">100+</div>
            <div class="a140">140+</div>
        </div>
        <div id="match_2">
            <div class="pkte">&nbsp;</div>
            <div class="name">&nbsp;</div>
            <div class="sets">0</div>
            <div class="legs">0</div>
            <hr />
            <div class="avg">0,00</div>
            <div class="his">0</div>
            <div class="hif">0</div>
            <div class="a60">0</div>
            <div class="a100">0</div>
            <div class="a140">0</div>
        </div>
    </div>
    <div id="leg_2">
        <table id="tab2"></table>
    </div>
</div>

<div class="pyro">
    <div class="before"></div>
    <div class="after"></div>
</div>

<div id="div180">180</div>

@Scripts.Render("~/bundles/scorer")

<script>
    setRequestURL("@Url.Action("Match", "API", new { id = @ViewBag.MatchID })");
</script>